spring:
  datasource:
    url: jdbc:mysql://myspring-app-sqldb.mysql.database.azure.com:3306/test?serverTimezone=UTC
    username: ${DB_USERNAME}
    azure:
      passwordless-enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
